site:
  title: DataHandwerk Docs
  url: https://DataHandwerk.github.io
  start_page: dhw::index.adoc
  # start_page: dhw:sqldb:nav/objects-by-schema.adoc
  # start_page: dhw:arc:architecture.adoc
  keys:
    google_analytics: 'G-L4RM6Q8D27'
content:
  sources:
  - url: D:\Repos\GitHub\DataHandwerk\DataHandwerk-docs
    branches: HEAD
    start_path: docs
  # - url: https://github.com/DataHandwerk/DataHandwerk-docs
  #   branches: main
  #   start_path: docs
  - url: D:\Repos\GitHub\DataHandwerk\sqldb-docs
    branches: HEAD
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    :plantuml-server-url: http://www.plantuml.com/plantuml
    # You can use the kroki-fetch-diagram option to download the images from Kroki at build time. In other words, while viewing pages you won't rely on Kroki anymore.
    # However, in Antora, this is not currently compatible with inline SVG images.
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
  # - path: ui.yml
  #   contents: |
  #     static_files: [ .nojekyll ]
  # - path: .nojekyll
output:
  clean: true
  dir: ./docs
  # destinations:
  # - provider: archive
  #   path: ./public/blue.zip
urls:
  redirect_facility: static
runtime:
  fetch: true
