= Antora Playbook project for DataHandwerk documentation

This repository contains https://docs.antora.org/antora/2.3/playbook/[the Antora Playbooks] and the final project documentation, which was generated by https://antora.org/[Antora].

Since I decided to use the more powerful markup language https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Asciidoc] and against Markdown, the best framework for _docs-as-code with Asciidoc_ in my opinion is https://antora.org/[Antora]. This tool is created and maintained by the same developers who develop AsciiDoctor. I have come to the conclusion that if you want to run Docs-as-Code with Asciidoc, it will be hard to find anything better.

https://docs.antora.org/antora/2.3/how-antora-works/[How Antora Works]

____
Antora’s default site generator handles all aspects of creating a documentation site, from fetching and aggregating to converting and arranging the content to publishing the files of the generated site.
____

learn about https://docs.antora.org/antora/2.3/playbook/[the Antora Playbook]

____
An Antora playbook makes it easy for technical writers to control what content is included in your site, what user interface (UI) is applied to it, and where the site is published using a playbook file. The settings in the playbook file, in combination with CLI options and environment variables, tell Antora how to operate.
____

____
A playbook is usually located in a playbook project. A playbook project repository is responsible for generating a documentation site. It’s strictly a _configuration as code_ repository—​it does not contain any content. Instead, it contains a playbook file, and, in certain situations, supplemental UI files and extension code.
____

== local npm Packages

....
node -e "require('fs').writeFileSync('package.json', '{}')"
npm i -D @antora/cli@3.0.0-beta.1 @antora/site-generator-default@3.0.0-beta.1
npm i -D asciidoctor asciidoctor-kroki

npx antora antora-playbook-local.yml --stacktrace
npx antora antora-playbook-public.yml --stacktrace
npx antora antora-playbook-local.yml --stacktrace --log-file antora-local.log
npx antora antora-playbook-public.yml --stacktrace --log-file antora-public.log
....


== GitHub pages vs GtLab Pages

The first place to publish Datahandwerk documentation was GitHub, using GitHub pages. And this page is now promoted: https://datahandwerk.github.io/dhw/current/index.html[]

But GitHub pages doesn't support Netlify redirects, GitLab and Netlify do. That's why for testing the site is also published as GitLab page. Netlify redirects are very useful for version switching. https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/[Redirect Facility Key]

https://datahandwerk.gitlab.io/[]

A redirect from github to gitlab was implemented.
